# Generated by Django 3.1.1 on 2021-06-11 15:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Category')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='category/%Y/%m/%d/', verbose_name='Category Image')),
            ],
            options={
                'verbose_name': 'Primary Category',
                'verbose_name_plural': 'Primary Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Category')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='category/%Y/%m/%d/', verbose_name='Category Image')),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_category', to='product.category', verbose_name='Primary Category')),
            ],
            options={
                'verbose_name': 'Sub-Category',
                'verbose_name_plural': 'Sub-Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True, unique=True, verbose_name='Video Url')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/', verbose_name='Video File')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='video-image/%Y/%m/%d/', verbose_name='Video Image')),
                ('name', models.CharField(max_length=300, verbose_name='Lesson Name')),
                ('name_uz', models.CharField(max_length=300, null=True, verbose_name='Lesson Name')),
                ('name_en', models.CharField(max_length=300, null=True, verbose_name='Lesson Name')),
                ('name_ru', models.CharField(max_length=300, null=True, verbose_name='Lesson Name')),
                ('slug', models.SlugField(max_length=320)),
                ('short_info', models.CharField(max_length=500, verbose_name='Short Info About Lesson')),
                ('short_info_uz', models.CharField(max_length=500, null=True, verbose_name='Short Info About Lesson')),
                ('short_info_en', models.CharField(max_length=500, null=True, verbose_name='Short Info About Lesson')),
                ('short_info_ru', models.CharField(max_length=500, null=True, verbose_name='Short Info About Lesson')),
                ('body', models.TextField(verbose_name='Lesson Body')),
                ('body_uz', models.TextField(null=True, verbose_name='Lesson Body')),
                ('body_en', models.TextField(null=True, verbose_name='Lesson Body')),
                ('body_ru', models.TextField(null=True, verbose_name='Lesson Body')),
                ('price', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)], verbose_name='Price')),
                ('discount', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)], verbose_name='Discount')),
                ('paid', models.BooleanField(default=True, verbose_name='Paid')),
                ('free', models.BooleanField(default=False, verbose_name='Free')),
                ('downloaded', models.IntegerField(default=0, verbose_name='Downloaded')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_field', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='product.subcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['name', 'published_at', 'updated_at'],
            },
        ),
    ]
