# Generated by Django 3.1.1 on 2021-06-12 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='free',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='price',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='discount',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)], verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Free'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='Paid'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000)], verbose_name='Price'),
        ),
    ]
