# Generated by Django 3.1.1 on 2021-06-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='ordereditem',
            options={'ordering': ['-date_ordered'], 'verbose_name': 'Ordered Lesson', 'verbose_name_plural': 'Ordered Lessons'},
        ),
    ]
